name: Meshplay Extension Build Reusable
on:
  workflow_call:
    inputs:
      checkout_ref:
        required: true
        type: string
      pr_number:
        default: ""
        required: false
        type: string
      comment_id:
        default: "comment-pr"
        required: false
        type: string
    secrets:
      NODE_VERSION:
        required: true
      GO_VERSION:
        required: true
      ORG_REPO_TOKEN:
        required: true

jobs:
  build-meshplay-extension:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Meshplay-extensions code
        uses: actions/checkout@v4
        with:
          repository: khulnasoft/meshplay-extensions
          path: ./meshplay-extensions
          fetch-depth: 1
          ref: ${{ inputs.checkout_ref }}
          token: ${{ secrets.ORG_REPO_TOKEN }}

      - name: Checkout Meshplay code
        uses: actions/checkout@v4
        with:
          repository: meshplay/meshplay
          path: ./meshplay
          fetch-depth: 1
          token: ${{ secrets.ORG_REPO_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ secrets.GO_VERSION }}
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: 'meshplay-extensions/meshmap/package-lock.json'
      - name: Verify go.mod sync compatibility
        working-directory: meshplay-extensions
        run: |
          make graphql-sync-err
      - name: comment success
        if: ${{ success() && github.event.inputs.pr_number != '' }}
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":heavy_check_mark: GraphQL compatibility package check completed."
          append: true
      - name: comment Failure
        if: ${{ failure() && github.event.inputs.pr_number != '' }}
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":x: GraphQL validation compatibility package check Failed: Upcoming PR dependencies are out of sync with Meshplay Server default branch."
          append: true
      - name: Validate MeshplayUI Compatibility Package
        working-directory: ./meshplay-extensions
        run: make kanvas-validate-meshplayui-compatibility
      - name: comment success
        if: ${{ success() && github.event.inputs.pr_number != '' }}
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":heavy_check_mark: Kanvas compatibility package check completed."
          append: true
      - name: comment Failure
        if: ${{ failure() && github.event.inputs.pr_number != '' }}
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":x: Kanvas compatibility package check Failed: Upcoming PR dependencies are out of sync with Meshplay UI default branch."
          append: true
      - name: Build Meshplay Extension UI
        working-directory: ./meshplay-extensions
        run: make kanvas-prod # gql build is not done for now
      - name: Build Graphql Plugin
        working-directory: ./meshplay-extensions
        run: make graphql
      - name: Show runner tree
        run: tree /home/runner/.meshplay
      - name: relocate meshplay-extension-ui
        run: mv /home/runner/.meshplay/provider/Meshplay/*/provider /home/runner/provider
      - name: Show runner tree
        run: tree /home/runner/ -L 3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: meshplay-extension-ui
          path: /home/runner/provider
          if-no-files-found: error
      - name: comment progress
        if: ${{ success() && github.event.inputs.pr_number != '' }}
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":heavy_check_mark: Meshplay Extensions build complete."
          append: true
      - name: comment Failure
        if: ${{ failure() && github.event.inputs.pr_number != '' }}
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":x: Meshplay Extensions build Failed."
          append: true
