name: Extension Test On PR Dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      pr_number:
        required: false
        type: string
    secrets:
      PROVIDER_TOKEN:
        required: true
      NODE_VERSION:
        required: true
      GO_VERSION:
        required: true
      ORG_REPO_TOKEN:
        required: true
      CYPRESS_RECORD_KEY:
        required: true
      KHULNASOFT_CLOUD_USERNAME:
        required: true
      KHULNASOFT_CLOUD_PASSWORD:
        required: true
      KHULNASOFT_CLOUD_TESTING_BOT_EMAIL:
        required: true
      KHULNASOFT_CLOUD_TESTING_BOT_PASSWORD:
        required: true

jobs:
  comment-starting-point:
    runs-on: ubuntu-latest
    steps:
      - name: comment starting point
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: "Starting [Meshplay Extensions tests](https://github.com/khulnasoft/meshplay-extensions-packages/actions/runs/${{ github.run_id }})..."
          recreate: true
  build-ui-and-server:
    uses: meshplay/meshplay/.github/workflows/build-ui-server-reusable-workflow.yml@master
    secrets:
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      GO_VERSION: ${{ secrets.GO_VERSION }}
  comment-success:
    runs-on: ubuntu-latest
    needs: [build-ui-and-server]
    steps:
      - name: comment progress
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":heavy_check_mark: Meshplay UI and Meshplay Server builds complete."
          append: true
  build-meshplay-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meshplay-extensions code
        uses: actions/checkout@v4
        with:
          repository: khulnasoft/meshplay-extensions
          path: ./meshplay-extensions
          fetch-depth: 1
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.ORG_REPO_TOKEN }}

      - name: Checkout Meshplay code
        uses: actions/checkout@v4
        with:
          repository: meshplay/meshplay
          path: ./meshplay
          fetch-depth: 1
          token: ${{ secrets.ORG_REPO_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ secrets.GO_VERSION }}
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Build Meshplay Extension UI
        working-directory: ./meshplay-extensions
        run: make meshmap # gql build is not done for now
      - name: Build Graphql Plugin
        working-directory: ./meshplay-extensions
        run: make graphql
      - name: Show runner tree
        run: tree /home/runner/.meshplay
      - name: relocate meshplay-extension-ui
        run: mv /home/runner/.meshplay/provider/Meshplay/*/provider /home/runner/provider
      - name: Show runner tree
        run: tree /home/runner/ -L 3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: meshplay-extension-ui
          path: /home/runner/provider
          if-no-files-found: error
      - name: comment progress
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":heavy_check_mark: Meshplay Extensions build complete."
          append: true
      - name: comment Failure
        if: failure()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":x: Meshplay Extensions build Failed."
          append: true
  tests-ui-e2e:
    needs: [build-ui-and-server, build-meshplay-extension]
    name: UI end-to-end tests
    runs-on: ubuntu-latest
    outputs:
      test-results: ${{ steps.run_tests.outputs.test-results }}
    steps:
      - name: comment progress start
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":heavy_check_mark: Setting up test environment..."
          append: true
      - name: Check out Meshplay code
        uses: actions/checkout@v4
        with:
          repository: meshplay/meshplay
          fetch-depth: 1
          path: meshplay
      - name: Check out meshplay-consul code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: khulnasoft/meshplay-consul
          path: ./meshplay-consul
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshplay
          path: meshplay/server/cmd/
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ secrets.GO_VERSION }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: "kind-cluster"
      - name: Create a out/ folder in meshplay ui
        run: |
          mkdir -p meshplay/ui/out
          mkdir -p meshplay/provider-ui/out/

      - name: Download Meshplay-ui artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshplay-ui-build
          path: meshplay/ui/out/

      - name: Download Meshplay-provider-ui artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshplay-provider-ui build
          path: meshplay/provider-ui/out/

      - name: Update /etc/hosts
        run: echo "127.0.0.1 meshplaylocal.khulnasoft.com" | sudo tee -a /etc/hosts
      - name: Run meshplay-consul
        run: |
          mkdir -p /home/runner/.meshplay/bin
          cd ./meshplay-consul
          go run main.go &
          sleep 60
      - name: Set Release extensions
        run: |
          curl -s https://api.github.com/repos/khulnasoft/meshplay-extensions-packages/releases >> extension_releases.json
          export TAG=$(jq .[0].tag_name extension_releases.json)
          echo tag=$TAG >> $GITHUB_ENV
          echo $TAG
      - name: make directories
        run: |
          echo ${{env.tag}}
          echo ${{env}}
          mkdir -p /home/runner/.meshplay/provider/Meshplay/${{env.tag}}/provider/
      - name: Run backend
        working-directory: meshplay
        env:
          PROVIDER_BASE_URLS: https://meshplay.khulnasoft.com
          PORT: 9081
          ADAPTER_URLS: "meshplaylocal.khulnasoft.com:10000 meshplaylocal.khulnasoft.com:10001 meshplaylocal.khulnasoft.com:10002 meshplaylocal.khulnasoft.com:10003 meshplaylocal.khulnasoft.com:10004 meshplaylocal.khulnasoft.com:10008 meshplaylocal.khulnasoft.com:10009 meshplaylocal.khulnasoft.com:10007"
        run: |
          cd server/cmd
          chmod +x ./main
          BUILD=${{env.tag}} ./main &
      - name: Download Meshplay-extension-ui artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshplay-extension-ui
          path: provider
      - name: Move provider files
        run: |
          mv /home/runner/work/meshplay-extensions-packages/meshplay-extensions-packages/provider/ /home/runner/.meshplay/provider/Meshplay/${{env.tag}}/

      - name: Checkout Meshplay-extensions code
        uses: actions/checkout@v4
        with:
          repository: khulnasoft/meshplay-extensions
          path: ./meshplay-extensions
          fetch-depth: 1
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.ORG_REPO_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: show tree
        run: tree  -L 2

      - name: Install dependencies
        run: ls && cd meshplay-extensions && make test-setup

      - name: comment progress start
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":heavy_check_mark: Test environment ready. Starting tests..."
          append: true

      - name: Run  Tests
        id: run_tests
        working-directory: meshplay-extensions
        run: |
          echo 'test-results<<EOF' >> $GITHUB_OUTPUT
          make test >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        env:
          PROVIDER_TOKEN: ${{ secrets.PROVIDER_TOKEN }}
          MESHPLAY_SERVER_URL: "http://localhost:9081"
          REMOTE_PROVIDER_URL: "https://meshplay.khulnasoft.com"
          REMOTE_PROVIDER_USER_EMAIL: ${{ secrets.KHULNASOFT_CLOUD_TESTING_BOT_EMAIL }}
          REMOTE_PROVIDER_USER_PASSWORD: ${{ secrets.KHULNASOFT_CLOUD_TESTING_BOT_PASSWORD }}

      - name: comment the summary
        uses: hasura/comment-progress@v2.3.0
        if: always()
        with:
          message: |
            ${{join(steps.run_tests.outputs.*, '\n')}}

          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          append: true

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: meshplay-extensions/meshmap/test-results/
          retention-days: 30

      - name: Comment Test failure
        uses: hasura/comment-progress@v2.3.0
        if: ${{ failure()  }}
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":x: One or more tests have failed."
          append: true

      - name: Comment Final Status
        if: always()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.ORG_REPO_TOKEN }}
          repository: "khulnasoft/meshplay-extensions"
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ":heavy_check_mark: Extension [test results](https://github.com/khulnasoft/meshplay-extensions-packages/actions/runs/${{ github.run_id }})."
          append: true
