# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Publish Meshplay Design Embed React Package

on:
  workflow_dispatch:
    inputs:
      release-version:
        required: true

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          scope: "@khulnasoft"

      - name: Install Dependencies and Build Package
        run: |
          cd meshplay-design-embed &&
          npm install && 
          npm run build

      - name: Generate new version
        run: cd meshplay-design-embed &&  npm version ${{ github.event.inputs.release-version }}

      - name: Run npm release
        run: cd meshplay-design-embed && npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and push version change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: gitworkflows
          commit_user_email: gitworkflows@khulnasoft.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "[Release Meshplay Embed ]: release version  ${{ github.event.inputs.release-version }}"
