name: Meshplay Extension Release updater
on:
  release:
    types: [published]
jobs:
  Update:
    name: Release updater
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # token here with write access to meshplay-istio repo
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          ref: 'master'
          repository: 'khulnasoft/meshplay-extensions'
      - name: Update extensions_releases.json
        run: rm -f build/extension_releases.json && curl -s https://api.github.com/repos/khulnasoft/meshplay-extensions-packages/releases >> build/extension_releases.json;
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: gitworkflows
          commit_user_email: info@khulnasoft.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: 'updated extension_releases.json'
