name: Workflow Dispatcher
on: [repository_dispatch]

jobs:
  build-ui-and-server:
    if: github.event.action == 'dispatch-pr-test'
    uses: khulnasoft/meshplay-extensions-packages/.github/workflows/extension-test-on-pr.yml@master
    with:
      branch_name: ${{ github.event.client_payload.branch_name }}
      pr_number: ${{ github.event.client_payload.pr_number }}
    secrets:
      PROVIDER_TOKEN: ${{ secrets.PROVIDER_TOKEN }}
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      GO_VERSION: ${{ secrets.GO_VERSION }}
      ORG_REPO_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      KHULNASOFT_CLOUD_USERNAME: ${{ secrets.KHULNASOFT_CLOUD_USERNAME }}
      KHULNASOFT_CLOUD_PASSWORD: ${{ secrets.KHULNASOFT_CLOUD_PASSWORD }}
      KHULNASOFT_CLOUD_TESTING_BOT_EMAIL: ${{ secrets.KHULNASOFT_CLOUD_TESTING_BOT_EMAIL }}
      KHULNASOFT_CLOUD_TESTING_BOT_PASSWORD: ${{ secrets.KHULNASOFT_CLOUD_TESTING_BOT_PASSWORD }}

  meshplay-cloud-deploy:
    if: github.event.action == 'meshplay-cloud-deploy'
    uses: khulnasoft/meshplay-extensions-packages/.github/workflows/meshplay-cloud-release.yml@master
    with:
      release-environment: ${{ github.event.client_payload.release_environment }}
      release-version: ${{ github.event.client_payload.release_version}}
    secrets:
      ORG_REPO_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      MESHPLAY_CLOUD_AWS_PROD_HOST: ${{ secrets.MESHPLAY_CLOUD_AWS_PROD_HOST }}
      MESHPLAY_CLOUD_AWS_PROD_USERNAME: ${{ secrets.MESHPLAY_CLOUD_AWS_PROD_USERNAME }}
      MESHPLAY_CLOUD_AWS_PROD_KEY: ${{ secrets.MESHPLAY_CLOUD_AWS_PROD_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      MESHPLAY_CLOUD_AWS_STG_HOST: ${{ secrets.MESHPLAY_CLOUD_AWS_STG_HOST }}
